#!/usr/bin/env bash
python test_mention_frequency.py ../data/20201117_conservative_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201117_conservative_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201117_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201117_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201121_conservative_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201121_conservative_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201121_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201121_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201122_conservative_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201122_conservative_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201122_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201122_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201123_conservative_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201123_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201123_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201124_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201124_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201126_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201126_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201126_politics_top.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201126_politics_rising.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201126_politics_controversial.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201127_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201127_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201127_politics_top.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201127_politics_rising.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201127_politics_controversial.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201130_politics_hot.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201130_politics_new.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201130_politics_top.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201130_politics_rising.json >> analysis_result.txt
python test_mention_frequency.py ../data/20201130_politics_controversial.json >> analysis_result.txt